import TauCetiRoadmap.MartingaleProblems.Suggested

open Filter Topology MeasureTheory ProbabilityTheory Set
open scoped NNReal ENNReal

variable {Ω : Type*} {m : MeasurableSpace Ω} {𝕂 : Type*} [RCLike 𝕂]
  {ι : Type*} [LinearOrder ι] [TopologicalSpace ι]

/-- **The products of bounded measurable functions of finitely many coordinates** with times in
`S`: `x ↦ ∏_{i ∈ u} h_i (π_i x)` for a finite `u ⊆ S`. -/
def pastProducts {F G : Type*} [MeasurableSpace G] (π : ι → F → G) (S : Set ι) : Set (F → ℝ) :=
  {Z | ∃ (u : Finset ι) (h : ι → G → ℝ), (↑u ⊆ S) ∧ (∀ i, Measurable (h i)) ∧
    (∀ i, ∃ C, ∀ y, |h i y| ≤ C) ∧ Z = fun x ↦ ∏ i ∈ u, h i (π i x)}

omit [LinearOrder ι] [TopologicalSpace ι] in
theorem isMulSystem_pastProducts {F G : Type*} [MeasurableSpace G] (π : ι → F → G) (S : Set ι) :
    IsMulSystem (pastProducts π S) := by
  classical
  rintro _ ⟨u, h, hu, hm, hb, rfl⟩ _ ⟨v, h', hv, hm', hb', rfl⟩
  let k : ι → G → ℝ := fun i y ↦ (if i ∈ u then h i y else 1) * (if i ∈ v then h' i y else 1)
  refine ⟨u ∪ v, k, ?_, fun i ↦ ?_, fun i ↦ ?_, ?_⟩
  · rw [Finset.coe_union]; exact Set.union_subset hu hv
  · by_cases h1 : i ∈ u <;> by_cases h2 : i ∈ v <;> simp only [k, h1, h2] <;>
      first
        | exact (hm i).mul (hm' i)
        | exact (hm i).mul measurable_const
        | exact measurable_const.mul (hm' i)
        | exact measurable_const.mul measurable_const
  · obtain ⟨C, hC⟩ := hb i
    obtain ⟨C', hC'⟩ := hb' i
    refine ⟨max C 1 * max C' 1, fun y ↦ ?_⟩
    simp only [k, abs_mul]
    refine mul_le_mul ?_ ?_ (abs_nonneg _) (le_trans zero_le_one (le_max_right _ _))
    · split_ifs
      · exact (hC y).trans (le_max_left _ _)
      · simp
    · split_ifs
      · exact (hC' y).trans (le_max_left _ _)
      · simp
  · funext x
    simp only [Pi.mul_apply, k, Finset.prod_mul_distrib]
    congr 1
    · rw [← Finset.prod_subset (Finset.subset_union_left) (fun i _ hi ↦ by simp [hi])]
      exact Finset.prod_congr rfl fun i hi ↦ by simp [hi]
    · rw [← Finset.prod_subset (Finset.subset_union_right) (fun i _ hi ↦ by simp [hi])]
      exact Finset.prod_congr rfl fun i hi ↦ by simp [hi]

/-- **`isDetermining_products`: the products of bounded measurable functions of finitely many
coordinates are a determining set**, for a filtration that is pulled back along the path map from
the σ-algebras generated by the coordinates at the times in `S s`.  The natural filtration is
`S s = Set.Iic s`.  The proof is `isDetermining_of_generateFromFuns`: the products are a
multiplicative class (`isMulSystem_pastProducts`), contain `1` as the empty product, and generate
the coordinate σ-algebra because the indicator of `{π r ∈ B}` is one of them. -/
theorem isDetermining_products {F G : Type*} [MeasurableSpace F] [MeasurableSpace G]
    {π : ι → F → G} {S : ι → Set ι} {𝓖 : ι → MeasurableSpace F}
    (h𝓖 : ∀ s : ι, 𝓖 s = ⨆ r ∈ S s, MeasurableSpace.comap (π r) inferInstance)
    {X : Ω → F} {𝓕 : Filtration ι m}
    (h𝓕 : ∀ s : ι, (𝓕 s : MeasurableSpace Ω) = MeasurableSpace.comap X (𝓖 s))
    {𝓧 : Set (ι → Ω → 𝕂)} (hadp : ∀ Y ∈ 𝓧, StronglyAdapted 𝓕 Y) :
    IsDetermining (fun s ↦ pastProducts π (S s)) 𝓧 X 𝓕 := by
  classical
  have hπ : ∀ s, ∀ r ∈ S s, Measurable[𝓖 s] (π r) := fun s r hr ↦ by
    rw [h𝓖 s]
    exact measurable_iff_comap_le.2 (le_iSup₂ (f := fun r (_ : r ∈ S s) ↦
      MeasurableSpace.comap (π r) (inferInstance : MeasurableSpace G)) r hr)
  have hKm : ∀ s, ∀ Z ∈ pastProducts π (S s), Measurable[𝓖 s] Z := by
    rintro s _ ⟨u, h, hu, hm, -, rfl⟩
    exact Finset.measurable_prod u fun i hi ↦ (hm i).comp (hπ s i (hu hi))
  refine isDetermining_of_generateFromFuns h𝓕 (fun s ↦ isMulSystem_pastProducts π (S s))
    hKm ?_ ?_ ?_ hadp
  · rintro s _ ⟨u, h, -, -, hb, rfl⟩
    choose C hC using hb
    refine ⟨∏ i ∈ u, C i, fun x ↦ ?_⟩
    rw [Finset.abs_prod]
    exact Finset.prod_le_prod₀ (fun i _ ↦ abs_nonneg _) fun i _ ↦ hC i _
  · intro s
    refine le_antisymm (generateFromFuns_le_iff.2 (hKm s)) ?_
    rw [h𝓖 s]
    refine iSup₂_le fun r hr ↦ measurable_iff_comap_le.1 ?_
    intro B hB
    have hmem : (fun x ↦ ∏ i ∈ ({r} : Finset ι), (B.indicator (1 : G → ℝ)) (π i x))
        ∈ pastProducts π (S s) := by
      refine ⟨{r}, fun _ ↦ B.indicator 1, by simpa using hr, fun _ ↦ measurable_const.indicator hB,
        fun _ ↦ ⟨1, fun y ↦ ?_⟩, rfl⟩
      by_cases hy : y ∈ B <;> simp [hy]
    have h1 := measurable_generateFromFuns_of_mem hmem (measurableSet_singleton (1 : ℝ))
    convert h1 using 1
    ext x
    simp only [Finset.prod_singleton, Set.mem_preimage, Set.mem_singleton_iff]
    by_cases hx : π r x ∈ B <;> simp [hx]
  · intro s
    exact ⟨∅, fun _ _ ↦ 1, by simp, fun _ ↦ measurable_const, fun _ ↦ ⟨1, fun _ ↦ by simp⟩,
      by simp⟩
